on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        try: [1,2,3,4,5,6,7,8,9,10]
    runs-on: ubuntu-latest

    steps:
      - run: docker pull ghcr.io/cybozu-go/coil:2.0.3
